# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 41806528dc14c45d64a40717c5a9f01ab77422f5ec68890dc0601ba7929e65852e5509fb3c572074d88281e46756b0eb753f57bb7195f37ffd70dafcf496005e

test:
  secret_key_base: 7372c904fa6f427c4c77f53175a6b9d246a276581cea60688834186c33de84d1208a3c1dfe15e277d2a25fb9075a2afec709cffd338a685864fc46b13615ca64

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
